#!/bin/bash

ROOT="$(cd "$(dirname "$0")"; pwd)"

set -e
set -x

cd "$ROOT"
git submodule update --init --recursive
ln -sf "$ROOT/vimrc" ~/.vimrc
ln -sf "$ROOT/gvimrc" ~/.gvimrc

git config include.path "../.gitconfig"
