#!/bin/bash

ROOT="$(cd "$(dirname "$0")"; pwd)"

set -e
set -x

cd "$ROOT"
git submodule update --init --recursive
(cd "$ROOT/bundle/command-t/ruby/command-t" && false && ruby extconf.rb && make)
ln -s "$ROOT/vimrc" ~/.vimrc
